version: '2'
services:
  elasticsearch-masters:
    image: winhong/wh-elasticsearch
    stdin_open: true
    volumes:
    - /var/lib/winhong/elasticsearch/master-data:/usr/share/elasticsearch/data:z
    - /root/es-test/elasticsearch-node.tmpl:/etc/confd/templates/elasticsearch.tmpl
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=elasticsearch-masters
      io.rancher.scheduler.affinity:host_label: usage=log
  elasticsearch-clients:
    privileged: true
    image: elasticsearch/elasticsearch:sq-test1
    environment:
      XPACK_SECURITY_ENABLED: 'true'
    stdin_open: true
    tty: true
    volumes:
    - /root/es-test/elasticsearch-node.tmpl:/etc/confd/templates/elasticsearch.tmpl
    ports: 
    - 9200:9200/tcp
    user: root
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=elasticsearch-clients
      io.rancher.scheduler.affinity:host_label: usage=log
  elasticsearch-data:
    privileged: true
    image: elasticsearch/elasticsearch:sq-test1
    environment:
      XPACK_SECURITY_ENABLED: 'true'
    stdin_open: true
    volumes:
    - /var/lib/winhong/elasticsearch/data:/usr/share/elasticsearch/data:z
    - /root/es-test/elasticsearch-node.tmpl:/etc/confd/templates/elasticsearch.tmpl
    tty: true
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=elasticsearch-data
      io.rancher.scheduler.affinity:host_label: usage=log
  dockerlog-fluentd:
    privileged: true
    image: winhong/dockerlog-fluentd
    stdin_open: true
    volumes:
    - /var/lib/docker:/var/lib/docker:ro
    - /var/log/fluentd:/var/log/fluentd
    tty: true
    pid: host
    user: root
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  systemd-fluentd:
    privileged: true
    image: winhong/systemd-fluentd
    stdin_open: true
    volumes:
    - /var/log/fluentd:/var/log/fluentd:rw
    - /run/log/journal:/run/log/journal
    tty: true
    pid: host
    user: root
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  kibana-5:
    image: winhong/wh-kibana
    environment:
      XPACK_SECURITY_ENABLED: 'true'
    stdin_open: true
    tty: true
    ports: 
    - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: usage=log

