version: '2'
catalog:
  name: wingrow
  version: v1.3-beta
  description: |
    WinHong's cicd system ,part of WinGarden suite.
  services:
  mariadb:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 3306
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  sonar:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 9000
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  wingrow:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 8100
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  jenkins-client:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 2375
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  jenkins-master:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  web:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 5000
      strategy: recreate
      reinitializing_timeout: 60000
  questions:
    - variable: "REGISTRY_INSCURE"
      type: boolean
      required: true
      label: "Registry inscure "
      description: "Docker Registry scured ,if access by http ,the value is true"
      default: "true" 
    - variable: "LDAP_URL"
      type: string
      label: "LDAP URL "
      description: "LDAP server address,used when use openldap/AD to do user authentication "
      default: "ldap://X.X.X.X:389"      
    - variable: "LDAP_SEARACHBASE"
      type: string
      label: "LDAP Search Base  "
      description: "LDAP search base  "
      default: ""    
    - variable: "LDAP_USER"
      type: string
      label: "LDAP user "
      description: "LDAP search base  "
      default: ""   
    - variable: "LDAP_PASSWORD"
      type: password
      label: "LDAP User's password "
      description: "LDAP search base  "
      default: ""   
    - variable: "LDAP_TIMEOUT"
      type: int
      label: "LDAP TIMEOUT "
      description: "LDAP connetction timeout ,microsecond "
      default: 200  
    - variable: "TOKEN_EXPIRY"
      type: int
      required: true
      label: "Token Expiry(Minutes)"
      description: "Token expiry time, default is half hour "
      default: 30 
    - variable: "SLAVE_EXECUTORS"
      type: int
      required: true
      label: "Slave's executes   "
      description: "Excutes number of jenkins slave "
      default: 1 
    - variable: "FORCE_INIT"
      type: boolean
      required: true
      label: "Force Init "
      description: "Reinit Wingrow by environment vars after restart "
      default: false   
