version: '2'
services:
  sonar:
    image: wh-cicd/sonar:5.6.6-mariadb
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: password
      SONARQUBE_JDBC_URL: jdbc:mysql://mariadb:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    stdin_open: true
    tty: true
    links:
    - mariadb:mariadb
    ports:
    - 9000:9000/tcp
    labels:
      io.rancher.container.pull_image: always
  mariadb:
    image: wh-cicd/mariadb:10.3.1-sonar
    stdin_open: true
    tty: true
    ports:
    - 3306:3306/tcp
    labels:
      io.rancher.container.pull_image: always
  jenkins-slave:
    privileged: true
    image: wh-cicd/jenkis-slave
    environment:
      JENKINS_MASTER: http://jenkins-master:8080
      REGISTRY_AUTH: ${REGISTRY_AUTH}
      REGISTRY_INSCURE: '${REGISTRY_INSCURE}'
      REGISTRY_IP: ${REGISTRY_IP}
      REGISTRY_PORT: '${REGISTRY_PORT}'
      SLAVE_EXECUTORS: '${SLAVE_EXECUTORS}'
      WINGARDEN_URL: ${WINGARDEN_URL}
      SECRETKEY: ${SECRETKEY}
      ACCESSKEY: ${ACCESSKEY}
    stdin_open: true
    tty: true
    links:
    - jenkins-master:jenkins-master
    labels:
      io.rancher.container.pull_image: always
  wingrow-backend:
    image: wingrow/wingrow
    environment:
      SONAR_URL: HTTP://sonar:8080
      SONAR_USER: wingrow
      SONAR_PASSWORD: wer123231sd
      JENKINS_MASTER: http://jenkins-master:8080
      JENKINS_USERNAME: jenkins
      JENKINS_PASSWORD: w12sedwiokd
      WINGARDEN_URL: ${WINGARDEN_URL}
      ACCESSKEY: ${ACCESSKEY}
      SECRETKEY: ${SECRETKEY}
      REGISTRY_AUTH: ${REGISTRY_AUTH}
      REGISTRY_IP: ${REGISTRY_IP}
      REGISTRY_PORT: '${REGISTRY_PORT}'
      REGISTRY_INSCURE: '${REGISTRY_INSCURE}'
      SMTP_SSL: '${SMTP_SSL}'
      SMTP_PORT: '${SMTP_PORT}'
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      LDAP_URL: ${LDAP_URL}
      LDAP_SEARACHBASE: ${LDAP_SEARACHBASE}
      LDAP_USER: ${LDAP_USER}
      LDAP_PASSWORD: ${LDAP_PASSWORD}
      LDAP_TIMEOUT: '${LDAP_TIMEOUT}'
      FORCE_INIT: '${FORCE_INIT}'
      TOKEN_EXPIRY: '${TOKEN_EXPIRY}'
    stdin_open: true
    tty: true
    links:
    - jenkins-master:jenkins-master
    ports:
    - 8100:8100/tcp
    labels:
      io.rancher.container.pull_image: always
  jenkins-master:
    image: wh-cicd/jenkis-master
    stdin_open: true
    volumes:
    - /var/jenkins_home
    tty: true
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.pull_image: always
