version: '2'
catalog:
  name: wingrow
  version: v1.1-beta
  description: |
    WinHong's cicd system ,part of WinGarden suite.
  services:
    sonarqube-56:
      scale: 1
      start_on_create: true
    sonar-mariadb2:
      scale: 1
      start_on_create: true
    jenkins-client:
      scale: 1
      start_on_create: true
    wingrow:
      scale: 1
      start_on_create: true
    jenkins-master:
      scale: 1
      start_on_create: true
  questions:
    - variable: "WINGARDEN_URL"
      type: string
      label: "WinGarden server URL"
      description: "WinGarden server URL, prefix should be http:// "
      required: true
    - variable: "ACCESSKEY"
      type: string
      label: "ACCESSKEY"
      description: "ACCESSKEY of WinGarden"
      default: ""
      required: true
    - variable: "SECRETKEY"
      type: password
      label: "SECRETKEY"
      description: "SECRETKEY of WinGarden"   
      default: ""
      required: true
    - variable: "REGISTRY_IP"
      type: string
      label: "Registry IP"
      description: "Docker Registry IP"
      default: ""
      required: true
    - variable: "REGISTRY_PORT"
      type: int
      label: "Registry Port"
      description: "Docker Registry Port"
      default: 80
      required: true
    - variable: "REGISTRY_AUTH"
      type: password
      required: true
      label: "Registry Auth"
      description: "Docker Registry Auth ,you can find auth in ~/.docker/config.json"
      default: "80" 
      required: true
    - variable: "REGISTRY_INSCURE"
      type: boolean
      required: true
      label: "Registry scured "
      description: "Docker Registry scured ,if access by https ,the value is false"
      default: "false" 
    - variable: "LDAP_URL"
      type: string
      label: "LDAP URL "
      description: "LDAP server address,used when use openldap/AD to do user authentication "
      default: "ldap://X.X.X.X:389"      
    - variable: "LDAP_SEARACHBASE"
      type: string
      label: "LDAP Search Base  "
      description: "LDAP search base  "
      default: ""    
    - variable: "LDAP_SEARACHBASE"
      type: string
      label: "LDAP Search Base  "
      description: "LDAP search base  "
      default: ""    
    - variable: "LDAP_USER"
      type: string
      label: "LDAP user "
      description: "LDAP search base  "
      default: ""   
    - variable: "LDAP_PASSWORD"
      type: password
      label: "LDAP User's password "
      description: "LDAP search base  "
      default: ""   
    - variable: "LDAP_TIMEOUT"
      type: int
      label: "LDAP TIMEOUT "
      description: "LDAP connetction timeout ,microsecond "
      default: 200  
    - variable: "SMTP_HOST"
      type: string
      label: "SMTP Server"
      description: "Reuqired by notify feature,ip or domain name  "
      default: "200"    
    - variable: "SMTP_PORT"
      type: int
      label: "SMTP Port "
      description: "Reuqired by notify feature "
      default: 365
    - variable: "SMTP_USER"
      type: string
      label: "SMTP User "
      description: "Reuqired by notify feature "
      default: ""    
    - variable: "SMTP_PASSWORD"
      type: password
      label: "SMTP Password "
      description: "Reuqired by notify feature "
      default: ""   
    - variable: "SMTP_SSL"
      type: boolean
      label: "SMTP SSL "
      description: "TURE for use  SSL"
      default: false 
    - variable: "TOKEN_EXPIRY"
      type: int
      required: true
      label: "Token Expiry(Minutes)"
      description: "Token expiry time, default is half hour "
      default: 30 
    - variable: "SLAVE_EXECUTORS"
      type: int
      required: true
      label: "Slave's executes   "
      description: "Excutes number of jenkins slave "
      default: 1 