.catalog:
  name: "WinGrow cicd"
  version: "v0.1.1"
  description: "WinGrow system"
  WinGrow:
    scale: 1
    start_on_create: true
  dockerregistry:
    external_ips:
    - 10.0.2.50
    start_on_create: true
  gitlab:
    scale: 1
    start_on_create: true
  sonar:
    scale: 1
    start_on_create: true
