version: '2'
services:
  elasticsearch-clients:
    image: winhong/wh-elasticsearch
    environment:
      XPACK_SECURITY_ENABLED: 'true'
    stdin_open: true
    volumes:
    - /var/lib/winhong/elasticsearch/client-data:/usr/share/elasticsearch/data:z
    - /root/es-test/jvm-es-stack.options:/usr/share/elasticsearch/config/jvm.options
    - /root/es-test/elasticsearch.tmpl:/etc/confd/templates/elasticsearch.tmpl
    tty: true
    ports: 
    - 9200:9200/tcp
    user: root
    labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:host_label: usage=log
      {{- if eq .Values.UPDATE_SYSCTL "true" -}}
            ,es-sysctl
      {{- end}}
    environment:
      - "cluster.name=${cluster_name}"
      - "node.name=$${HOSTNAME}"
      - "ES_JAVA_OPTS=-Xms${client_heap_size} -Xmx${client_heap_size}"
      - "discovery.zen.ping.unicast.hosts=elasticsearch-clients"
      - "discovery.zen.minimum_master_nodes=${minimum_master_nodes}"
    ulimits:
        memlock:
            soft: -1
            hard: -1
        nofile:
            soft: 65536
            hard: 65536
    mem_limit: ${client_mem_limit}
        mem_swappiness: 0
    cap_add:
      - IPC_LOCK
  dockerlog-fluentd:
    privileged: true
    image: winhong/dockerlog-fluentd
    stdin_open: true
    volumes:
    - /var/lib/docker:/var/lib/docker:ro
    - /var/log/fluentd:/var/log/fluentd
    tty: true
    pid: host
    user: root
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  systemd-fluentd:
    privileged: true
    image: winhong/systemd-fluentd
    stdin_open: true
    volumes:
    - /var/log/fluentd:/var/log/fluentd:rw
    - /run/log/journal:/run/log/journal
    tty: true
    pid: host
    user: root
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
  kibana-5:
    image: winhong/wh-kibana
    environment:
      XPACK_SECURITY_ENABLED: 'true'
    stdin_open: true
    tty: true
    ports: 
    - 5601:5601/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: usage=log
  {{- if eq .Values.UPDATE_SYSCTL "true" }}
  es-sysctl:
    labels:
      io.rancher.container.start_once: true
    network_mode: none
    image: winhong/alpine-sysctl:0.1
    privileged: true
    environment:
      - "SYSCTL_KEY=vm.max_map_count"
      - "SYSCTL_VALUE=655350"
  {{- end}}


