version: '2'
services:
    press-container:
      image: elasticsearch/es-press:biglog
      stdin_open: true
      tty: true
      environment:
        RUN_NUM: $lognum
      labels:
        io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:host_label: usage=test
        app: es-press
